version: '3.8'
services:
  dynamodb-local:
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    # working_dir: /home/dynamodblocal
    # command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    # volumes:
    #   - "./docker/dynamodb:/home/dynamodblocal/data"
  treble:
    depends_on:
      - dynamodb-local
    container_name: treble
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      AWS_ACCESS_KEY_ID: 'XXXXXXXXXXXXXXX'
      AWS_SECRET_ACCESS_KEY: 'XXXXXXXXXXXXXXXXXXXXXX'
  ngrok:
    image: "ngrok/ngrok:latest"
    container_name: ngrok
    restart: unless-stopped
    command: "start --all --config /etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    environment:
      NGROK_AUTHTOKEN: '2PF8jgYZTpOFZSClDRjknVduZd6_6P1NSH1imZ7U7PTX7VQR6'
    ports:
        - 4040:4040